name: Test Third-Party Action Access

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: This is an official action that will likely work
        uses: actions/checkout@v4

      - name: This is a very popular, non-official action
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: This is the Google Sheets action we want to use
        uses: gautamkrishnar/append-csv-to-google-sheet-action@v2
        with:
          # We don't need real inputs, we just want to see if it can be found
          sheet-name: 'Test' 
          csv-text: 'test'
          spreadsheet-id: 'test'
          google-api-key-base64: 'test'
